const canvas=document.querySelector('#traceCanvas'),ctx=canvas.getContext('2d'),statusEl=document.querySelector('#status');
const select=document.querySelector('#motif'),scale=document.querySelector('#scale'),duration=document.querySelector('#duration');
const images={},W=1600,H=900,ink='#20221f',paper='#eee9df',red='#d4422e';
let points=[],pointerDown=false,lastPoint=null,cursor={x:800,y:440},showCursor=false,ready=false;
const sources=['ce-drawing.jpg','cr-line.jpg','ln-line.jpg'];
Promise.all(sources.map(name=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{images[name]=img;resolve()};img.onerror=reject;img.src='assets/'+name}))).then(()=>{ready=true;statusEl.textContent='Ready. Leave an impression to begin.';render(performance.now())}).catch(()=>{statusEl.textContent='A source drawing could not load. Reload the page after checking the assets folder.'});
function addPoint(x,y){if(!ready)return;points.push({x:Math.max(0,Math.min(W,x)),y:Math.max(100,Math.min(790,y)),size:Number(scale.value),image:select.value,born:performance.now(),life:Number(duration.value)});if(points.length>240)points.shift();statusEl.textContent=`${points.length} impressions in your composition.`;render(performance.now())}
function render(now,editing=true){ctx.globalAlpha=1;ctx.fillStyle=paper;ctx.fillRect(0,0,W,H);ctx.save();ctx.beginPath();ctx.rect(0,90,W,710);ctx.clip();points=points.filter(p=>p.life===0||(now-p.born)<p.life*1000);for(const p of points){const opacity=p.life===0?1:Math.max(0,1-(now-p.born)/(p.life*1000));ctx.save();ctx.globalAlpha=opacity;ctx.beginPath();ctx.arc(p.x,p.y,p.size/2,0,Math.PI*2);ctx.clip();ctx.fillStyle=red;ctx.fillRect(p.x-p.size/2,p.y-p.size/2,p.size,p.size);const img=images[p.image];if(img){ctx.globalCompositeOperation='multiply';const sw=img.naturalWidth*.55,sh=img.naturalHeight*.55;const sx=(p.x/W)*(img.naturalWidth-sw),sy=(p.y/H)*(img.naturalHeight-sh);ctx.drawImage(img,sx,sy,sw,sh,p.x-p.size/2,p.y-p.size/2,p.size,p.size)}ctx.restore()}ctx.restore();
 ctx.globalAlpha=1;ctx.fillStyle=ink;ctx.textAlign='left';ctx.font='48px Georgia';ctx.fillText('MIR',55,65);ctx.font='18px Arial';ctx.textAlign='right';ctx.fillText('WHAT REMAINS. / A PERSONAL IMPRESSION',1545,57);ctx.strokeStyle=ink;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(55,90);ctx.lineTo(1545,90);ctx.moveTo(55,800);ctx.lineTo(1545,800);ctx.stroke();ctx.font='48px Georgia';ctx.textAlign='left';ctx.fillText('An impression that remains.',55,865);ctx.font='18px Arial';ctx.textAlign='right';ctx.fillText('MIR / 01',1545,857);
 if(points.length===0&&editing){ctx.textAlign='center';ctx.fillStyle='#605f58';ctx.font='italic 58px Georgia';ctx.fillText('A gesture becomes a memory.',800,465)}
 if(editing&&showCursor){ctx.strokeStyle=ink;ctx.lineWidth=2;ctx.setLineDash([7,7]);ctx.beginPath();ctx.arc(cursor.x,cursor.y,Number(scale.value)/2,0,Math.PI*2);ctx.stroke();ctx.setLineDash([])}
}
function position(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();canvas.focus();canvas.setPointerCapture(e.pointerId);pointerDown=true;cursor=position(e);lastPoint=cursor;addPoint(cursor.x,cursor.y)});
canvas.addEventListener('pointermove',e=>{cursor=position(e);if(pointerDown&&(!lastPoint||Math.hypot(cursor.x-lastPoint.x,cursor.y-lastPoint.y)>Number(scale.value)*.25)){addPoint(cursor.x,cursor.y);lastPoint={...cursor}}});
canvas.addEventListener('pointerup',()=>{pointerDown=false;lastPoint=null});canvas.addEventListener('pointercancel',()=>{pointerDown=false;lastPoint=null});
canvas.addEventListener('keydown',e=>{const keys=['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Enter'];if(!keys.includes(e.key))return;e.preventDefault();showCursor=true;const d=e.shiftKey?80:25;if(e.key==='ArrowUp')cursor.y-=d;if(e.key==='ArrowDown')cursor.y+=d;if(e.key==='ArrowLeft')cursor.x-=d;if(e.key==='ArrowRight')cursor.x+=d;cursor.x=Math.max(0,Math.min(W,cursor.x));cursor.y=Math.max(100,Math.min(790,cursor.y));if(e.key===' '||e.key==='Enter')addPoint(cursor.x,cursor.y);render(performance.now())});
canvas.addEventListener('focus',()=>{showCursor=true;render(performance.now())});canvas.addEventListener('blur',()=>{showCursor=false;render(performance.now())});
scale.oninput=()=>{document.querySelector('#scaleValue').value=scale.value;render(performance.now())};
document.querySelector('#stamp').onclick=()=>addPoint(800,440);
document.querySelector('#clear').onclick=()=>{points=[];statusEl.textContent='Composition reset. Leave a new impression.';render(performance.now())};
document.querySelector('#save').onclick=()=>{if(!ready){statusEl.textContent='Wait for the artwork to load before saving.';return}render(performance.now(),false);try{canvas.toBlob(blob=>{if(!blob){statusEl.textContent='Could not export the postcard.';return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='MIR-your-impression.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);statusEl.textContent='Postcard saved at 1600 × 900 pixels.';render(performance.now())})}catch(e){statusEl.textContent='Open the local web-server preview to save images.';render(performance.now())}};
function tick(now){if(points.some(p=>p.life>0))render(now);requestAnimationFrame(tick)}render(performance.now());requestAnimationFrame(tick);
